### ISSUE TITLE
As a user, I want to see auto-categorized todo list, because it takes time to categorize each items.

### ISSUE THREAD

**Issue by afsanhk** [mhmozaffari1985/LHL-midterm-project#23]
Exact API calls for:
- [x] Books - Afsan
- [x] Film - Afsan
- [x] TV Series - Afsan
- [x] Restaurants (limited to GTA) - Afsan

More general API call but can categorize things like products:
- [x] Google knowledge - Mohammad 

- [ ] Combine exact API call with google knowledge - Mohammad
- [ ] Edit route so that autocategorization works when new task is added.
