### ISSUE TITLE
As a user, I want to view my to-do list.

### ISSUE THREAD

**Issue by afsanhk** [mhmozaffari1985/LHL-midterm-project#9]
- [x] Set up full to-do list view (index.ejs).
- [x] Script to load all to-do tasks in index.ejs.
- [x] Set up categorized to-do list view (categoryView.ejs).
- [x] Script to load all categorized to-do in categoryView.
